model_module:
    models.category_embedding.category_embedding
normalize_content:
    false
data:
    train:
        "./data/prepared/train_features.pkl"
    val:
        "./data/prepared/val_features.pkl"
experiment_root:
    "./experiments/cat_emb_features_only"
study_seed:
    4242
n_trials:
    100
default_trials:
    [
        {
            "num_layers": 1,
            "num_hidden_exp_1": 9,
            "lr_exp": -3,
            "alpha_exp": -3,
            "batch_exp": 8
        },
        {
            "num_layers": 3,
            "num_hidden_exp_1": 10,
            "num_hidden_exp_2": 6,
            "num_hidden_exp_3": 5,
            "lr_exp": -3,
            "alpha_exp": -3,
            "batch_exp": 5
        }
    ]