model_module:
    models.tabnet.tabnet
normalize_content:
    true
data:
    train:
        "./data/prepared/content_train_df.pkl"
    val:
        "./data/prepared/content_val_df.pkl"
experiment_root:
    "./experiments/tabnet_content_only"
study_seed:
    4242
n_trials:
    100
default_trials:
    [
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 8,
         "n_d_exp": 3,
         "n_a_exp": 3,
         "n_steps": 3,
         "gamma": 1.3
        },
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 8,
         "n_d_exp": 6,
         "n_a_exp": 6,
         "n_steps": 10,
         "gamma": 2
        },
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 6,
         "n_d_exp": 2,
         "n_a_exp": 2,
         "n_steps": 3,
         "gamma": 1.0
        },
    ]

"categorical_cols": []
