model_module:
    models.tabnet.tabnet
normalize_content:
    false
data:
    train:
        "./data/prepared/train_features.pkl"
    val:
        "./data/prepared/val_features.pkl"
experiment_root:
    "./experiments/tabnet_features_only"
study_seed:
    4242
n_trials:
    100
default_trials:
    [
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 8,
         "n_d_exp": 3,
         "n_a_exp": 3,
         "n_steps": 3,
         "gamma": 1.3
        },
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 8,
         "n_d_exp": 6,
         "n_a_exp": 6,
         "n_steps": 10,
         "gamma": 2
        },
        {
         "lr_exp": -3,
         "alpha_exp": -3,
         "batch_exp": 6,
         "n_d_exp": 2,
         "n_a_exp": 2,
         "n_steps": 3,
         "gamma": 1.0
        },
    ]
