model_module:
    models.lgbm.lgbm
normalize_content:
    true
data:
    train:
        "./data/prepared/content_train_df.pkl"
    val:
        "./data/prepared/content_val_df.pkl"
experiment_root:
    "./experiments/lgbm_content_only"
study_seed:
    4242
n_trials:
    1000
default_trials:
    [
        {
         num_leaves: 500,
         max_depth: 12,
         min_child_samples: 5,
         n_estimators: 1000,
         learning_rate: 0.01,
         reg_alpha: 0,
         reg_lambda: 0,
         min_split_gain: 0,
         subsample: 0.8,
         colsample_bytree: 1.0
        },
        {
         num_leaves: 500,
         max_depth: 12,
         min_child_samples: 5,
         n_estimators: 2000,
         learning_rate: 0.001,
         reg_alpha: 0,
         reg_lambda: 0,
         min_split_gain: 0,
         subsample: 0.8,
         colsample_bytree: 1.0
        },
        {
         num_leaves: 1000,
         max_depth: 10,
         min_child_samples: 5,
         n_estimators: 1000,
         learning_rate: 0.01,
         reg_alpha: 0,
         reg_lambda: 0,
         min_split_gain: 0,
         subsample: 0.8,
         colsample_bytree: 1.0
        }
    ]

clf_params:
    verbosity:
        -1

fit_verbose:
    False
